name: my_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  go_router: ^16.2.2
  get: ^4.7.2
  sqflite: ^2.3.0
  path: ^1.9.0
  http: ^1.2.0
  dio: ^5.3.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0 
  google_fonts: ^6.2.1
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_2.png
    - assets/background.jpg
    - assets/new_background.jpg
    - assets/facebook.png
    - assets/google.png
